// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Head from "next/head";
import $$Image from "next/image";
import * as HomeModuleCss from "../styles/Home.module.css";

var styles = HomeModuleCss;

function $$default(param) {
  return React.createElement("div", {
              className: styles.container
            }, React.createElement(Head, {
                  children: null
                }, React.createElement("title", undefined, "Create Next App"), React.createElement("meta", {
                      content: "Generated by create next app",
                      name: "description"
                    }), React.createElement("link", {
                      href: "/favicon.ico",
                      rel: "icon"
                    })), React.createElement("main", {
                  className: styles.main
                }, React.createElement("h1", {
                      className: styles.title
                    }, "Welcome to", React.createElement("a", {
                          href: "https://nextjs.org"
                        }, "Next.js!")), React.createElement("p", {
                      className: styles.description
                    }, "Get started by editing", React.createElement("code", {
                          className: styles.code
                        }, "pages/index.js")), React.createElement("div", {
                      className: styles.grid
                    }, React.createElement("a", {
                          className: styles.card,
                          href: "https://nextjs.org/docs"
                        }, React.createElement("h2", undefined, "Documentation &rarr;"), React.createElement("p", undefined, "Find in-depth information about Next.js features and API.")), React.createElement("a", {
                          className: styles.card,
                          href: "https://nextjs.org/learn"
                        }, React.createElement("h2", undefined, "Learn &rarr;"), React.createElement("p", undefined, "Learn about Next.js in an interactive course with quizzes!")), React.createElement("a", {
                          className: styles.card,
                          href: "https://github.com/vercel/next.js/tree/canary/examples"
                        }, React.createElement("h2", undefined, "Examples &rarr;"), React.createElement("p", undefined, "Discover and deploy boilerplate example Next.js projects.")), React.createElement("a", {
                          className: styles.card,
                          href: "https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        }, React.createElement("h2", undefined, "Deploy &rarr;"), React.createElement("p", undefined, "Instantly deploy your Next.js site to a public URL with Vercel.")))), React.createElement("footer", {
                  className: styles.footer
                }, React.createElement("a", {
                      href: "https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, "Powered by", React.createElement("span", {
                          className: styles.logo
                        }, React.createElement($$Image, {
                              src: "/vercel.svg",
                              alt: "Vercel Logo",
                              width: 72,
                              height: 16
                            })))));
}

export {
  $$default ,
  $$default as default,
  
}
/* styles Not a pure module */
