// Generated by ReScript, PLEASE EDIT WITH CARE


var PlayButton = {};

var Timer = {};

var Soundplayer = {
  PlayButton: PlayButton,
  Timer: Timer
};

export {
  Soundplayer ,
  
}
/* No side effect */
